<?php

namespace app\models;

use Yii;
use yii\data\Pagination;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $content
 * @property string $date
 * @property integer $viewed
**/


class News extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'content', 'author',], 'required', 'message' => 'Please, fill in all the fields'],
            [['title', 'content', 'description'], 'string'],
            [['date'], 'date', 'format'=>'php:Y-m-d'],
            [['date'], 'default', 'value'=> date('Y-m-d')],
            [['title'], 'string', 'max'=> 255],
            [['image'], 'file', 'extensions' => 'png, jpg,jpeg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'image' => 'Image',
            'description' => 'Description',
            'author' => 'Author',
            'content' => 'Content',
            'date' => 'Date',
            'viewed' => 'Viewed',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function saveImage($filename) {
        $this->image = $filename;
        $this->save(false);
    }

    public function deleteImage() {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function getImage()
    {
        return ($this->image) ? '/images/' . $this->image : '/no-image.png';
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public static function getAll($pageSize = 5) {
        $query = News::find();
        $count = $query->count();

        $pagination = new Pagination(['totalCount' => $count, 'pageSize' => $pageSize]);

        $news = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        $data['news'] = $news;
        $data['pagination'] = $pagination;

        return $data;
    }

    public static function getPosts()
    {
        return News::find()->orderBy('viewed desc')->limit(3)->all();
    }

    public function getDate()
    {
        return Yii::$app->formatter->asDate($this->date);
    }


    public function viewedCounter()
    {
        $this->viewed += 1;
        return $this->save(false);
    }

    public function getComments() {
        return $this->hasMany(Comment::className(), ['news_id' => 'id']);
    }
}
